blank_issues_enabled: false
contact_links:
  - name: "Affective Technologies: Stewarded Services project"
    url: https://github.com/users/dghauri0/projects/5
    about: Review priorities, status, and work across stewarded services.
