// Generates dist/ from src/.
//
// Two consumer shapes, one source:
//   dist/admin-kit.{css,js,html}  real files, for static hosts that just
//                                 <link>/<script> them (Cloudflare Pages)
//   dist/strings.js               ES module exporting the same three as
//                                 strings, for hosts that inject markup
//                                 server-side (Cloudflare Workers)
//
// The string form is GENERATED, so the source files are ordinary CSS/JS and
// are not subject to the "no backticks / ${} inside" constraint that the
// hand-maintained Worker version had to live under.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = (f) => readFileSync(join(root, 'src', f), 'utf8');
mkdirSync(join(root, 'dist'), { recursive: true });

const parts = { css: read('admin-kit.css'), js: read('admin-kit.js'), html: read('admin-kit.html') };

for (const [ext, body] of Object.entries(parts)) {
  writeFileSync(join(root, 'dist', `admin-kit.${ext}`), body);
}

// Escape for safe embedding in a template literal.
const lit = (s) => '`' + s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${') + '`';

writeFileSync(join(root, 'dist', 'strings.js'), `// GENERATED by scripts/build.mjs — do not edit. Source of truth is src/.
export const ADMIN_KIT_CSS = ${lit(parts.css)};
export const ADMIN_KIT_HTML = ${lit(parts.html)};
export const ADMIN_KIT_JS = ${lit(parts.js)};
`);

console.log('built dist/ from src/');
